config/routes.rb
Rails.application.routes.draw do
  root "quotes#index"
  # add the seven routes of the CRUD for our Quote resource
  resources :quotes

  # How NOT to close or erase a turbo_frame 
  # get 'close_form', to: 'quotes#close_edit', as: 'close_quote_edit_form'
  # get 'close_frame_tag', to: 'application#close_turbo_frame', as: 'close_turbo_frame'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/qoute.rb
class Qoute < ApplicationRecord
    validates :name, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :name, presence: true

    scope :ordered, -> { order(id: :desc) }

    # REDIS SHOULD BE INSTALLED AND RUNNING
    # redis-server

    # This should be executed every time a new quote is inserted into the database.

    # after_create_commit -> { 
    #     broadcast_prepend_to "quotes", 
    #     partial: "quotes/quote", 
    #     locals: { quote: self }, 
    #     target: "quotes" }
    
    #     As we can see above, we specify the target name to be "quotes" thanks to 
    #     the target: "quotes" option. By default, the target option will be equal 
    #     to model_name.plural, which is equal to "quotes" in the context of our 
    #     Quote model. Thanks to this convention, we can remove the target: "quotes" option

    #     There are two other conventions we can use to shorten our code. Under the hood, 
    #     Turbo has a default value for both the partial and the locals option.
        
    #     The partial default value is equal to calling to_partial_path on an instance of 
    #     the model, which by default in Rails for our Quote model is equal to "quotes/quote".
        
    #     The locals default value is equal to { model_name.element.to_sym => self } which, 
    #     in in the context of our Quote model, is equal to { quote: self }.
        
    #     These are precisely the values that we passed as options. Thus, the following 
    #     code is equivalent to what we had before:
    after_create_commit -> { 
        broadcast_prepend_to "quotes"
        broadcast_update_to "quotes", partial: "quotes/quotes_count", target: "quotes_count"
    }
    after_update_commit -> { broadcast_replace_to "quotes" }
    after_destroy_commit -> { broadcast_remove_to "quotes" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # def close_turbo_frame
    #     frame_id = params[:frame_id]
    #     render turbo_stream: turbo_stream.update( frame_id , "" )
    # end
end

app/controllers/qoutes_controller.rb
class QoutesController < ApplicationController
    before_action :set_qoute, only: [:show, :edit, :update, :destroy]

    def index
        @qoutes = Qoutes.all
    end

    def show
    end

    def new
        @qoute = Qoute.new
    end

    def create
        @qoute = Qoute.new(qoute_params)
        if @qoute.save
            redirect_to qoutes_path, notice: "Qoute was successfully created"
        else
            rednder :new
        end
    end

    def edit
    end

    def update
        if @qoute.update(qoute_params)
            redirect_to qoutes_path, notice: "The qoute was successfully updated"
        else
            render :edit
        end
    end

    def destroy
        @quote.destroy
        redirect_to quotes_path, notice: "Quote was successfully destroyed."
    end

    private

        def set_quote
            @quote = Quote.find(params[:id])
        end

        def quote_params
            params.require(:quote).permit(:name)
        end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :set_quote, only: [:show, :edit, :update, :destroy]
    
    def index
        @quotes = Quote.ordered
    end

    def show
    end

    def new
        @quote = Quote.new
    end

    def create
        @quote = Quote.new(quote_params)

        respond_to do |format|
            if @quote.save
                # A way to respond is just "format.turbo_stream". This Turbo stream way
                #scope :ordered, -> { order(id: :desc) } will render a view file called create.turbo_stream.erd (in my case is *.slim)
                # where we will instruct Turbo to do two things: append on "quotes" frame and
                # update the "new_quote" frame.
                format.turbo_stream 
                # Or we can directly render the turbo streams like this:
                # format.turbo_stream do
                #     render turbo_stream: [
                #         turbo_stream.update( Quote.new, ""),
                #         turbo_stream.append( 'quotes', partial: "quotes/quote", 
                #                             locals: { quote: @quote } )                       
                #     ]
                # end
                format.html{ redirect_to quotes_path, notice: "Quote was successfully created" }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def edit
    end

    def update
        if @quote.update(quote_params)
            redirect_to quotes_path, notice: "The quote was successfully updated"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @quote.destroy
        # redirect_to quotes_path, notice: "Quote was successfully destroyed."
        respond_to do |format|
            # format.turbo_stream { render turbo_stream: turbo_stream.remove( @quote ) }
            format.turbo_stream do
                render turbo_stream: [
                    turbo_stream.remove( @quote ),
                    turbo_stream.update( "quotes_count", partial: "quotes/quotes_count" )           
                ]
            end
            format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
        end
    end

    # def close_edit
    #     redirect_to quotes_path
    # end

    private
        def set_quote
            @quote = Quote.find(params[:id])
        end

        def quote_params
            params.require(:quote).permit(:name)
        end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealTimeUpdatesTsAc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.slim
= simple_form_for @quote, html: { class: "quote form" } do |f|
    - if quote.errors.any?
        .error-message
            = quote.errors.full_messages.to_sentence.capitalize
    = f.input :name, input_html: { autofocus: true }
    = f.submit class: "btn btn--secondary"
    = link_to "Cancel", quotes_path, class: "btn btn--light"

/   When our user clicks on the "Cancel" link for the new quote form:

/     The link is within a Turbo Frame of id new_quote, so Turbo will only replace the content of this frame
/     The link navigates to the Quotes#index page that contains an empty Turbo Frame with id new_quote
/     Turbo replaces the content of the new_quote frame with the empty content, so the form disappears

/   When our user clicks on the "Cancel" link for the edit quote form:

/     The link is within a Turbo Frame of id dom_id(quote), so Turbo will only replace the content of this frame
/     The link navigates to the Quotes#index page that contains a Turbo Frame with id dom_id(quote) that contains the HTML for this quote
/     Turbo replaces the content of the dom_id(quote) Frame containing the form with the HTML for this quote


    / Another NO god way to erase our Turbo Frame is by a method in the controller and a path
    / - unless @quote.id
    /     = link_to "cancel", \
    /         close_turbo_frame_path( frame_id: dom_id(Quote.new) ), \
    /         class: "btn btn--light"
    / - else
    /     = link_to "cancel", \
    /         close_quote_edit_form_path( id: @quote ), \
    /         class: "btn btn--light"

app/views/quotes/_quote.html.slim
= turbo_frame_tag quote do
    .quote
        = link_to quote.name, quote_path(quote), data: { turbo_frame: "_top" }
        .quote__actions
            = link_to "Edit",\
                edit_quote_path(quote),\
                class: "btn btn--light"
            = button_to "Delete",\
                # quote_path(quote),\
                quote,\
                method: :delete,\
                data: {turbo_method: :delete},\
                class: "btn btn--light"
    

app/views/quotes/_quotes_count.html.slim
h4
    = "Total quotes: #{Quote.count}"

app/views/quotes/create.turbo_stream.slim
= turbo_stream.prepend "quotes", @quote
= turbo_stream.update Quote.new, ""
= turbo_stream.update "quotes_count", partial: "quotes/quotes_count"

/ If we feel the first line is too long
/ = turbo_stream.append "quotes", partial: "quotes/quote", locals: { quote: @quote }
/
/ we can use a block like:
/= turbo_stream.prepend "quotes" do
/     = render partial: "quotes/quote", locals: { quote: @quote }
/
/ And considerating that the following two expressions are equivalent:
/
/ render partial: "quotes/quote", locals: { quote: @quote }
/ render @quote
/ 
/ We could write something like
/ = turbo_stream.prepend "quotes" do
/     = render @quote
/ Or even better: 
/ = turbo_stream.append "quotes", @quote

app/views/quotes/edit.html.slim
main.container
    = link_to sanitize("&larr; Back to quotes"), quotes_path
    .header
        h1
            = "Edit quote"
    = turbo_frame_tag @quote do
        = render "form", quote: @quote

app/views/quotes/index.html.slim
= turbo_stream_from "quotes"
main.container 
    .header
        h1
            | Quotes
        = link_to "New Quote", new_quote_path,\
            data: { turbo_frame: dom_id(Quote.new)}, \
            class: "btn btn--primary"
    = turbo_frame_tag 'quotes_count'
        = render "quotes_count"
    = turbo_frame_tag Quote.new
    = turbo_frame_tag 'quotes'
    = render @quotes

    / # Compared to using a frontend library like React, 
    / # there is no state to manage, no complex actions to dispatch, 
    / # no reducers... Turbo is a joy to work with!

app/views/quotes/new.html.slim
.container
    = link_to sanitize("&larr; Back to quotes"), quotes_path
    .header
        h1
            = "New Quote"
    = turbo_frame_tag Quote.new do
        = render "form", quote: @quote

app/views/quotes/show.html.slim
main.container
    = link_to sanitize("&larr; Back to quotes"), quotes_path
    .header
        h1
            = @quote.name